export const americanCities = [
    "New York, USA",
    "Los Angeles, USA",
    "Chicago, USA",
    "Houston, USA",
    "Phoenix, USA",
    "Philadelphia, USA",
    "San Antonio, USA",
    "San Diego, USA",
    "Dallas, USA",
    "San Jose, USA",
    "Austin, USA",
    "Jacksonville, USA",
    "Fort Worth, USA",
    "Columbus, USA",
    "Indianapolis, USA",
    "Charlotte, USA",
    "San Francisco, USA",
    "Seattle, USA",
    "Denver, USA",
    "Washington, USA",
    "Boston, USA",
    "El Paso, USA",
    "Nashville, USA",
    "Detroit, USA",
    "Oklahoma City, USA",
    "Portland, USA",
    "Las Vegas, USA",
    "Memphis, USA",
    "Louisville, USA",
    "Baltimore, USA",
    "Milwaukee, USA",
    "Albuquerque, USA",
    "Tucson, USA",
    "Fresno, USA",
    "Sacramento, USA",
    "Mesa, USA",
    "Kansas City, USA",
    "Atlanta, USA",
    "Long Beach, USA",
    "Colorado Springs, USA",
    "Raleigh, USA",
    "Miami, USA",
    "Virginia Beach, USA",
    "Omaha, USA",
    "Oakland, USA",
    "Minneapolis, USA",
    "Tulsa, USA",
    "Wichita, USA",
    "New Orleans, USA",
    "Arlington, USA",
    "Cleveland, USA",
    "Bakersfield, USA",
    "Tampa, USA",
    "Aurora, USA",
    "Honolulu, USA",
    "Anaheim, USA",
    "Santa Ana, USA",
    "Corpus Christi, USA",
    "Riverside, USA",
    "St. Louis, USA",
    "Lexington, USA",
    "Pittsburgh, USA",
    "Anchorage, USA",
    "Cincinnati, USA",
    "Durham, USA",
    "Plano, USA",
    "Newark, USA",
    "Greensboro, USA",
    "Orlando, USA",
    "Irvine, USA",
    "North Las Vegas, USA",
    "Jersey City, USA",
    "Rochester, USA",
    "Boise, USA",
    "Chandler, USA",
    "Hialeah, USA",
    "Norfolk, USA",
    "Akron, USA",
    "Laredo, USA",
    "Madison, USA",
    "Fort Wayne, USA",
    "Baton Rouge, USA",
    "Scottsdale, USA",
    "Chula Vista, USA",
    "Garland, USA",
    "St. Petersburg, USA",
    "Reno, USA",
    "North Charleston, USA",
    "Birmingham, USA",
    "Spokane, USA",
    "Rochester, USA",
    "Springfield, USA",
    "Lincoln, USA",
    "Concord, USA",
    "Dayton, USA",
    "Savannah, USA",
    "Des Moines, USA",
    "Grand Rapids, USA",
    "Fayetteville, USA",
    "Richmond, USA",
    "Yonkers, USA",
    "Shreveport, USA",
    "Augusta, USA",
    "Huntsville, USA",
    "Knoxville, USA"
];
